### ISSUE TITLE
Error on opam install

### ISSUE THREAD

**Issue by tofgarion** [mpelleau/AbSolute#14]
Hello,

I cannot install AbSolute via opam. As I can build AbSolute from the sources, I have compared both sources from master branch and the opam package sources :

* the `dune` file in the opam package contains the line

```
(c_names src/ml_float)
```
instead of

```
(c_names ml_float)
```

which leads to a dune error

* changing the line removes the dune error, but `Pervasives` is still used in the source files which leads to deprecation error.

My environment :

* OCaml 4.09
* dune 2.1.3
* apron 0.9.12

Best,

Christophe

**Comment by ghilesZ** [comment]
Hello,
Thank you Christophe for the issue. 
It is fixed on master and will be included in the next release.

Best,
Ghiles
