### ISSUE TITLE
Using dune to compile AbSolute

### ISSUE THREAD

**Issue by ptal** [mpelleau/AbSolute#7]
*Problem*: AbSolute is compiled with a Makefile, and script to support compilation with and without the VPL library.
Also if we want to `ppx_inline_test` as a test framework (issue #6), the compilation script will get heavier.

*Proposed solution*: I suggest to use [Dune](https://github.com/ocaml/dune) which is a modern OCaml build system. The advantages include:
  * It has a very complete [documentation](https://media.readthedocs.org/pdf/dune/latest/dune.pdf).
  * It provides in its documentation an explanation on how to set `ppx_inline_test` and `Menhir`.
  * A lot of cool features to generate documentation, dealing with workspaces, ...
  * Conditional compilation supported with something like that:
```
(library
 ((name absolute)
  (libraries (vpl (select vpl_domain.ml from
                   (vpl  -> vpl_domain.ok.ml)
                   (!vpl -> vpl_domain.ko.ml))))))
```

**Comment by ptal** [comment]
AbSolute can now be compiled with `dune`. The changes are available on [this branch](https://github.com/mpelleau/AbSolute/tree/dune).
I am unsure about the OPAM support, I switched to OPAM 2.0 but could not test since it is not on master.
If everybody (@ghilesZ @mpelleau @MarechalAlex) is happy to go with `dune`, then I'll merge the branch in master, and then fix possible problems with OPAM 2.0.

How to use Dune
----------------------

Here a summary of what is good to know about dune:
* `dune build` to compile, and `dune runtest` to launch the tests (for now, it is only the "check.ml"); note that I removed the `Makefile`.
* `.merlin` files are generated automatically (which means it is in sync with the building script).
* output files are generated in `_build` (instead of being generated in the source code directory).
* From the manual: "The dune build and dune runtest commands support a -w (or --watch) flag. When it is passed, dune will perform the action as usual, and then wait for file changes and rebuild (or rerun the tests). This feature requires inotifywait or fswatch to be installed."
* `dune utop src/` starts a REPL with all the absolute libs loaded.

What's next
---------------

* I would like to allow warning only in debug mode in order to keep the code as clean as possible.
* Adding a Travis build script in order to be aware when you push changes that do not compile.

**Comment by ptal** [comment]
(A hundred of commits later: the repository sets with OPAM v2 is now working. Fiou.)

**Comment by mpelleau** [comment]
Do you have an idea why I cannot build absolute anymore...

```
dune build
File "src/dune", line 1, characters 0-0:
Error: Module "Vpl_drawer" appears in several directories:
- _build/default/src
- _build/default/src/print
make: *** [build] Error 1
```

**Comment by ghilesZ** [comment]
This one is weird, but i solved it by recloning the AbSolute's repo. For some reason, Dune finds old modules referenced somewhere but i suspect the error msg is not very accurate.

**Comment by MarechalAlex** [comment]
This is because previously, vpl_drawer.ml was copied from vpl_drawer.ok.ml or vpl_drawer.ko.ml. But Dune automatically handles this (ne need to cp vpl_drawer.ok.ml into vpl_drawer.ml anymore). 
To fix this, simply delete the file vpl_drawer.ml and vpl_domain.ml from your local files.
